name: distributed_agents
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - grpcio
  - protobuf
  - uvicorn
  - fastapi
  - pydantic
  - aiohttp
  - requests
  - numpy
  - pandas
  - psutil
  - pip:
      - autogenstudio
      - opentelemetry-api
      - opentelemetry-sdk
      - opentelemetry-exporter-otlp
      - opentelemetry-instrumentation
      - vllm
      - transformers
      - huggingface_hub
      - accelerate
      - aiofiles  # if using FastAPI static serving

